

#Configure To YOUR Enviornment and RUN
# docker compose -f solo-docker-compose.yml up -d
networks:
  private_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
    attachable: true
    internal: false
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.2.0.0/24
        - subnet: 2001:db8:abc::/64
          gateway: 2001:db8:abc::1


services:

  redis:
    image: redis:7-alpine
    container_name: wiregate-redis
    hostname: redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      #- redis_data:/data
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      private_network:
        ipv4_address: 10.2.0.4
        ipv6_address: 2001:db8:abc::4
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  wiregate:
      build:
        context: .
        dockerfile: Dockerfile
      #image: noxcis/wiregate:chimera
      container_name: wiregate
      hostname: wiregate
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      devices:
        - /dev/net/tun:/dev/net/tun  
      restart: unless-stopped
      volumes:
        - /lib/modules:/lib/modules:ro 
        - pf_conf:/WireGate/iptable-rules/
        #- conf:/etc/wireguard 
        #- db:/WireGate/db
        - ./configs/ssl:/WireGate/SSL_CERT
        - ./configs/dnscrypt:/WireGate/dnscrypt
        - ./configs/tor:/etc/tor/
        - ./configs/logs:/WireGate/log/
        - ./configs/master-key:/WireGate/master-key

      environment:
      #Config Path Optional
        #- WGDCONF_PATH=/etc/wireguard
      #Use Ofuscated Wireguard (AmneziaWG)
        - AMNEZIA_WG=true
      #Set Timezone
        - TZ=America/New_York
      #Dashboard Mode (development/production)
        - DASHBOARD_MODE=production  
      #Redis Database Settings
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_DB=0
        - REDIS_PASSWORD=wiregate_redis_password

      #Tor Settings
      ##########################################################
        - WGD_TOR_PROXY=true          #Enable Tor
        - WGD_TOR_EXIT_NODES={ch}     #Ex. {gb},{fr}
        - WGD_TOR_DNS_EXIT_NODES={us}
        - WGD_TOR_BRIDGES=false        #Enable Tor Bridges
        - WGD_TOR_PLUGIN=snowflake    #OPTIONS webtunnel, obfs4, snowflake
        - WGD_TOR_DNSCRYPT=false
      #WGDashboard Global Settings
      ##########################################################
        - WGD_WELCOME_SESSION=false
        - WGD_AUTH_REQ=false
        - WGD_USER=admin
        - WGD_PASS=admin
        - WGD_REMOTE_ENDPOINT=192.168.0.4
        - WGD_REMOTE_ENDPOINT_PORT=80
        - WGD_PEER_ENDPOINT_ALLOWED_IP=0.0.0.0/0, ::/0
        - WGD_KEEP_ALIVE=21
        - WGD_MTU=1420
        - WGD_PORT_RANGE_STARTPORT=4430
      #DNS Setiings (Set To use Containers Above) You can use your own DNS
      ##########################################################
        - WGD_DNS=1.1.1.1
        - WGD_IPTABLES_DNS=1.1.1.1
      ports:
        - 44333:44333/udp
        - "4430-4433:4430-4433/udp" #UDP Interface Listen Ports For Zones
        - 8000:80/tcp #Comment Out for full network lockdown, I.E only Accessible via VPN conttenction at http://wire.gate using config in generated master-key folder
      sysctls:        #Otherwise access the dashboard @ your-sever-ip/domain:6060
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv6.conf.all.forwarding=1
        - net.ipv6.conf.default.forwarding=1
      networks:
        private_network:
          ipv4_address: 10.2.0.3
          ipv6_address: 2001:db8:abc::3



volumes:
    #db:
    #conf:
    pf_conf:
    #redis_data:
  
