#Configure To YOUR Enviornment and RUN
# docker compose -f solo-docker-compose.yml up -d
networks:
  private_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
    attachable: true
    internal: false
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.2.0.0/24
        - subnet: 2001:db8:abc::/64
          gateway: 2001:db8:abc::1

services:
  unbound-dnscrypt:
    container_name: unbound-dnscrypt
    hostname: unbound-dnscrypt
    image: noxcis/unbound-dnscrypt:latest
    restart: unless-stopped
    volumes:
      - ./configs/dnscrypt-unbound/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml:ro
      - ./configs/dnscrypt-unbound/unbound.conf:/etc/unbound/unbound.conf:ro
      - ./configs/dnscrypt-unbound/custom.conf.d:/etc/unbound/custom.conf.d:ro
    #sysctls:
      #- net.core.rmem_max=8388608  # 8MB (needs to be at least 2x desired buffer)
      #- net.core.wmem_max=8388608
      #- net.core.rmem_default=4194304
      #- net.core.wmem_default=4194304
    cap_add:
      - NET_BIND_SERVICE
      - NET_ADMIN
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
        private_network:
          ipv4_address: 10.2.0.42
          ipv6_address: 2001:db8:abc::42

  adguard:
    depends_on: [unbound]
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    # Volumes store your data between container upgrades
    volumes:
      - "./configs/adguard/Data:/opt/adguardhome/work"
      - "./configs/adguard:/opt/adguardhome/conf"
    networks:
      private_network:
        ipv4_address: 10.2.0.100   
        ipv6_address: 2001:db8:abc::100

  redis:
    image: redis:7-alpine
    container_name: wiregate-redis
    hostname: redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - ./.env
    volumes:
      - redis_data:/data
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      private_network:
        ipv4_address: 10.2.0.4
        ipv6_address: 2001:db8:abc::4
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "wiregate_redis_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:15-alpine
    container_name: wiregate-postgres
    hostname: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configs/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./configs/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      private_network:
        ipv4_address: 10.2.0.5
        ipv6_address: 2001:db8:abc::5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wiregate_user -d wiregate"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf

  wiregate:
      build:
        context: .
        dockerfile: Dockerfile
      #image: noxcis/wiregate:sol-beta-v2.1.4
      container_name: wiregate
      hostname: wiregate
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      devices:
        - /dev/net/tun:/dev/net/tun  
      restart: unless-stopped
      depends_on:
        postgres:
          condition: service_healthy
        redis:
          condition: service_healthy
      volumes:
        - /lib/modules:/lib/modules:ro 
        - pf_conf:/WireGate/iptable-rules/
        - conf:/etc/wireguard 
        - db:/WireGate/db
        - ./configs/ssl:/WireGate/SSL_CERT
        - ./configs/dnscrypt:/WireGate/dnscrypt
        - ./configs/tor:/etc/tor/
        - ./configs/logs:/WireGate/log/
        - ./configs/master-key:/WireGate/master-key
      env_file:
        - ./.env
      ports:
        #- 44333:44333/udp
        #- "4430-4433:4430-4433/udp" #UDP Interface Listen Ports For Zones
        - 8080:80/tcp   # HTTP port
        - 8443:443/tcp  # HTTPS port for SSL
      sysctls:        #Otherwise access the dashboard @ your-sever-ip/domain:6060
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv6.conf.all.forwarding=1
        - net.ipv6.conf.default.forwarding=1
      healthcheck:
        test: ["CMD-SHELL", "netstat -tuln 2>/dev/null | grep -q ':443 ' || netstat -tuln 2>/dev/null | grep -q ':80 ' || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 30s
      networks:
        private_network:
          ipv4_address: 10.2.0.3
          ipv6_address: 2001:db8:abc::3


volumes:
    db:
    conf:
    pf_conf:
    redis_data:
    postgres_data:
  
    
  

