

#Configure To YOUR Enviornment and RUN
# docker compose -f solo-docker-compose.yml up -d
networks:
  private_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
    attachable: true
    internal: false
    ipam:
      config:
        - subnet: 10.5.0.0/24


services:
  wiregate:
      build: ./WG-Dash
      #image: noxcis/wg-dashboard:terra-fuego-beta
      container_name: wiregate
      hostname: wiregate
      devices:
        - /dev/net/tun:/dev/net/tun
      cap_add:
        - NET_ADMIN
      restart: unless-stopped
      volumes:
        - wgd_configs:/etc/wireguard 
        - wgd_db:/opt/wireguarddashboard/src/db 
        - ./Global-Configs/Tor:/etc/tor/
        - ./Global-Configs/Logs:/opt/wireguarddashboard/src/log/

      environment:
      #Config Path Optional
       #- WGD_CONF_PATH="/etc/wireguard"
      #Use Ofuscated Wireguard (AmneziaWG)
        - AMNEZIA_WG=true
      #Set Timezone
        - TZ=America/Chicago

      #Tor Settings
      ##########################################################
        - WGD_TOR_PROXY=true
        - WGD_TOR_EXIT_NODES={ch}
        - WGD_TOR_DNS_EXIT_NODES={us}
        - WGD_TOR_PLUGIN=webtunnel #OPTIONS webtunnel, obfs4, snowflake
        - WGD_TOR_BRIDGES=true

      #WGDashboard Global Settings
      ##########################################################
        - WGD_WELCOME_SESSION=false
        - WGD_AUTH_REQ=false
        - WGD_USER=admin
        - WGD_PASS=admin
        - WGD_REMOTE_ENDPOINT=0.0.0.0
        - WGD_REMOTE_ENDPOINT_PORT=80
        - WGD_PEER_ENDPOINT_ALLOWED_IP="0.0.0.0/0, ::/0"
        - WGD_KEEP_ALIVE=21
        - WGD_MTU=1420
        - WGD_PORT_RANGE_STARTPORT=4430

      #DNS Setiings (Set To use Containers Above) You can use your own DNS
      ##########################################################
        - WGD_DNS=1.1.1.1
        - WGD_IPTABLES_DNS=1.1.1.1

        
      #Obfuscated Wireguard via AmneziaWG Junk Headder Settings
      #All parameters should be the same between Client and Server, except Jc - it can vary.
      #########################################################
        - WGD_JC=5 #Jc — 1 ≤ Jc ≤ 128; recommended range is from 3 to 10 inclusive
        - WGD_JMIN=500 #Jmin — Jmin < Jmax; recommended value is 50
        - WGD_JMAX=550 #Jmax — Jmin < Jmax ≤ 1280; recommended value is 1000
        - WGD_S1=30 #S1 — S1 < 1280; S1 + 56 ≠ S2; recommended range is from 15 to 150 inclusive
        - WGD_S2=40 #S2 — S2 < 1280; recommended range is from 15 to 150 inclusive
        - WGD_H1=123456 #H1/H2/H3/H4 — must be unique among each other; recommended range is from 5 to 2147483647 inclusive
        - WGD_H2=67543 #H2
        - WGD_H3=32345 #H3
        - WGD_H4=123123 #H4
      ports:
        #- "4430-4433:4430-4433/udp" #UDP Interface Listen Ports
        - 8000:80/tcp #Comment Out for full network lockdown
      sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv6.conf.all.forwarding=1
        - net.ipv6.conf.default.forwarding=1
      networks:
        private_network:
          ipv4_address: 10.5.0.3
    


volumes:
    wgd_configs:
    wgd_db:
  
