
networks:
  private_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
    attachable: true
    internal: false
    ipam:
      config:
        - subnet: 10.2.0.0/24



services:
  unbound:
    image: "klutchell/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - ./Global-Configs/Unbound/custom-unbound.conf:/etc/unbound/custom.conf.d/custom-unbound.conf
    networks:
      private_network:
        ipv4_address: 10.2.0.200

  adguard:
    depends_on: [unbound]
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    volumes:
      - "./Global-Configs/AdGuard/Data:/opt/adguardhome/work"
      - "./Global-Configs/AdGuard/Config:/opt/adguardhome/conf"
    networks:
      private_network:
        ipv4_address: 10.2.0.100

  wiregate:
    image: noxcis/wg-dashboard:${TAG}
    container_name: wiregate
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - wgd_configs:/etc/wireguard
      - wgd_app:/opt/wireguarddashboard/src
      - ./Global-Configs/Master-Key:/opt/wireguarddashboard/src/master-key
    environment:
      - WGD_WELCOME_SESSION=false
      - WGD_APP_PORT=80
      - WGD_USER=${WGD_USER}
      - WGD_PASS=${WGD_PASS}
      - WGD_REMOTE_ENDPOINT=${WGD_REMOTE_ENDPOINT}
      - WGD_DNS="10.2.0.100, 10.2.0.100"
      - WGD_IPTABLES_DNS=10.2.0.100
      - WGD_PEER_ENDPOINT_ALLOWED_IP=0.0.0.0/0
      - WGD_KEEP_ALIVE=21
      - WGD_MTU=1420
      - WGD_PORT_RANGE_STARTPORT=${WGD_PORT_RANGE_STARTPORT}
    ports:
      - "${WGD_PORT_MAPPINGS}"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      private_network:
        ipv4_address: 10.2.0.3
    


  channels:
    depends_on: [db, wiregate]
    container_name: channels_messenger
    image: noxcis/channels:kraken
    restart: unless-stopped
    command: python run.py
    environment:
      - IS_DOCKER=1
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - SECRET_KEY=${MSG_SECRET_KEY}
      - DATABASE_URI=${DB_URI}
    networks:
      private_network:
        ipv4_address: 10.2.0.4
    dns: 10.2.0.100


  db:
    container_name: channels_db
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${MSG_DB_USER}
      - POSTGRES_PASSWORD=${MSG_DB_PASS}
      - POSTGRES_DB=db
    networks:
      private_network:
        ipv4_address: 10.2.0.5
    dns: 10.2.0.100

volumes:
    postgres_data:
    wgd_app:
    wgd_configs: