apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: wiregate
type: Opaque
data:
  # Base64 encoded password: wiregate_postgres_password
  password: d2lyZWdhdGVfcG9zdGdyZXNfcGFzc3dvcmQ=
