apiVersion: v1
kind: ConfigMap
metadata:
  name: wiregate-config
  namespace: wiregate
data:
  # Wiregate environment configuration
  WGD_TOR_PROXY: "true"
  WGD_TOR_EXIT_NODES: "{ch}"
  WGD_TOR_DNS_EXIT_NODES: "{us}"
  WGD_TOR_BRIDGES: "false"
  WGD_TOR_PLUGIN: "snowflake"
  WGD_TOR_DNSCRYPT: "false"
  WGD_WELCOME_SESSION: "false"
  WGD_AUTH_REQ: "false"
  WGD_USER: "admin"
  WGD_PASS: "admin"
  WGD_REMOTE_ENDPOINT: "192.168.0.4"
  WGD_REMOTE_ENDPOINT_PORT: "80"
  WGD_PEER_ENDPOINT_ALLOWED_IP: "0.0.0.0/0, ::/0"
  WGD_KEEP_ALIVE: "21"
  WGD_MTU: "1420"
  WGD_PORT_RANGE_STARTPORT: "4430"
  WGD_DNS: "1.1.1.1"
  WGD_IPTABLES_DNS: "1.1.1.1"
  AMNEZIA_WG: "true"
  TZ: "America/New_York"
  
  # Database Configuration - Shared PostgreSQL
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "wiregate"
  POSTGRES_USER: "wiregate_user"
  POSTGRES_SSL_MODE: "disable"
  
  # Redis Configuration - Will be overridden per instance
  REDIS_PORT: "6379"
  REDIS_DB: "0"
