version: "3"

networks:
  private_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
    attachable: true
    internal: false
    ipam:
      config:
        - subnet: 10.2.0.0/24
  

services:
  unbound:
    image: "klutchell/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - ./Global-Configs/Unbound/custom-unbound.conf:/etc/unbound/custom.conf.d/custom-unbound.conf
    networks:
      private_network:
        ipv4_address: 10.2.0.200

  pihole:
    depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:nightly
    restart: unless-stopped
    hostname: pihole
    dns:
      - 10.2.0.200 # Points to unbound
    environment:
      TZ: "${PI_HOLE_TZ}"
      WEBPASSWORD: "${PI_HOLE_PASS}"
      ServerIP: 10.2.0.100 # Internal IP of pihole
      DNS1: 10.2.0.200 # Unbound IP
      DNS2: 10.2.0.200 # If we don't specify two, it will auto pick google.
    volumes:
      - "./Global-Configs/PiHole/etc-pihole/:/etc/pihole/"
      - "./Global-Configs/PiHole/etc-pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    cap_add:
      - NET_ADMIN
    networks:
      private_network:
        ipv4_address: 10.2.0.100


        
  wiregate:
    image: noxcis/wg-dashboard:hydra
    container_name: wiregate
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - wg_configs:/etc/wireguard
      - wg_data:/home/app/dashboard-config
      - wg_db:/home/app/db
      - wg_iptables:/home/app/Iptables
      - ./Global-Configs/Master-Key:/home/app/master-key
    environment:
      - WG_DASH_USER=${WG_DASH_USER}
      - WG_DASH_PASS=${WG_DASH_PASS}
      - WG_DASH_SERVER_IP=${WG_DASH_SERVER_IP}
      - WG_DASH_DNS=10.2.0.100, 10.2.0.100
      - WG_DASH_IPTABLES_DNS=10.2.0.100
      - WG_DASH_PEER_ENDPOINT_ALLOWED_IP=0.0.0.0/0
      - WG_DASH_KEEP_ALIVE=21
      - WG_DASH_MTU=1420
      - WG_DASH_PORT_RANGE_STARTPORT=${WG_DASH_PORT_RANGE_STARTPORT}
    ports:
      - "${WG_DASH_PORT_MAPPINGS}"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      private_network:
        ipv4_address: 10.2.0.3
    dns: 10.2.0.100

  channels:
    depends_on: [db, wiregate]
    container_name: channels_messenger
    image: noxcis/channels:kraken
    restart: unless-stopped
    command: python run.py
    environment:
      - IS_DOCKER=1
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - SECRET_KEY=${MSG_SECRET_KEY}
      - DATABASE_URI=${DB_URI}
    networks:
      private_network:
        ipv4_address: 10.2.0.4
    dns: 10.2.0.100

  db:
    container_name: channels_db
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${MSG_DB_USER}
      - POSTGRES_PASSWORD=${MSG_DB_PASS}
      - POSTGRES_DB=db
    networks:
      private_network:
        ipv4_address: 10.2.0.5
    dns: 10.2.0.100


volumes:
    postgres_data:
    wg_data:
    wg_configs:
    wg_db:
    wg_iptables:
  
