listen_addresses = ['0.0.0.0:5053']
proxy = 'socks5://wiregate:9053'

force_tcp = true


netprobe_address = '10.2.0.3:9053'
netprobe_timeout = 60
timeout = 5000
keepalive = 30

max_clients = 250

ipv4_servers = true
ipv6_servers = false

dnscrypt_servers = false
doh_servers = true
odoh_servers = true

require_dnssec = false
require_nolog = true
require_nofilter = true

cert_refresh_delay = 240
dnscrypt_ephemeral_keys = true

block_ipv6 = true
block_unqualified = true
block_undelegated = true

reject_ttl = 10


cache = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

server_names = ['onion.cloudflare','odoh-cloudflare']


[static]
#[static.'odoh-cloudflare']
#stamp = 'sdns://BQcAAAAAAAAAF29kb2guY2xvdWRmbGFyZS1kbnMuY29tCi9kbnMtcXVlcnk'
[static.'onion.cloudflare']
stamp = 'sdns://AgcAAAAAAAAAAAA-ZG5zNHRvcnBubGZzMmlmdXoyczJ5ZjNmYzdyZG1zYmhtNnJ3NzVldWozNXBhYzZhcDI1emdxYWQub25pb24KL2Rucy1xdWVyeQ'




[anonymized_dns]
routes = [
    { server_name='odoh-cloudflare', via=['odohrelay-crypto-sx', 'odohrelay-se', 'odohrelay-ams'] }
]

#skip_incompatible = true

[broken_implementations]
fragments_blocked = ['cisco', 'cisco-ipv6', 'cisco-familyshield', 'cisco-familyshield-ipv6', 'cisco-sandbox', 'cleanbrowsing-adult', 'cleanbrowsing-adult-ipv6', 'cleanbrowsing-family', 'cleanbrowsing-family-ipv6', 'cleanbrowsing-security', 'cleanbrowsing-security-ipv6']

