listen_addresses = ['0.0.0.0:5053']

max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = false
doh_servers = false
odoh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true
cert_refresh_delay = 240
dnscrypt_ephemeral_keys = false
block_ipv6 = true
cache = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600


[sources]
### ODOH relays

[sources.'odoh-relays']
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/odoh-relays.md']
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    cache_file = 'odoh-relays.md'

[static]
[static.'odoh-cloudflare']
stamp = 'sdns://BQcAAAAAAAAAF29kb2guY2xvdWRmbGFyZS1kbnMuY29tCi9kbnMtcXVlcnk'


[anonymized_dns]
routes = [
    { server_name='odoh-cloudflare', via=['odohrelay-crypto-sx', 'odohrelay-se', 'odohrelay-ams'] }
]

skip_incompatible = true
