#!/bin/bash

start() {


tor &


tee /etc/resolv.conf &> /dev/null << EOF
 Generated by WireAdmin; DO NOT EDIT
nameserver 127.0.0.1
option allow-domains *.onion
search .
EOF


DNSMASQ_CONFIG=/etc/dnsmasq.d/tor-dns.conf
tee "$DNSMASQ_CONFIG" &> /dev/null << EOF
pid-file=/var/run/dnsmasq.pid
interface=eth0
user=dnsmasq
group=dnsmasq
bind-dynamic
no-resolv
no-poll
no-negcache
bogus-priv
log-queries
cache-size=1500
min-port=4096
server=10.2.0.45#53530
log-facility=/var/log/dnsmasq/dnsmasq.log
EOF
mkdir -p /var/log/dnsmasq


}
start