FROM resin/rpi-raspbian:latest
MAINTAINER Julien Delange <julien@gunnm.org>
COPY . /app
WORKDIR /app
RUN echo "deb http://mirrordirector.raspbian.org/raspbian/ stretch main contrib non-free rpi" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get install python3 python3-pip python3-setuptools
RUN pip3 install -r requirements.txt
RUN rm -f app.db
RUN python3 ./db_create.py
EXPOSE 5050
ENTRYPOINT ["python3"]
CMD ["run-production.py"]
