apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: wiregate
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
