
networks:
  private_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
    attachable: true
    internal: false
    ipam:
      config:
        - subnet: 10.2.0.0/24

services:
  unbound:
    image: "klutchell/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - ./Global-Configs/Unbound/custom-unbound.conf:/etc/unbound/custom.conf.d/custom-unbound.conf
    networks:
      private_network:
        ipv4_address: 10.2.0.200

  pihole:
    depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:nightly
    restart: unless-stopped
    hostname: pihole
    dns:
      - 10.2.0.200 # Points to unbound
    volumes:
      - "./Global-Configs/PiHole/etc-pihole/:/etc/pihole/"
      - "./Global-Configs/PiHole/etc-pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    env_file:
      - ./Global-Configs/WireGate-Deploy-ENV/wiregate.env
    cap_add:
      - NET_ADMIN
    networks:
      private_network:
        ipv4_address: 10.2.0.100

  
  wiregate:
    container_name: wiregate
    image: noxcis/wg-dashboard:${TAG}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - wgd_configs:/etc/wireguard
      - wgd_app:/opt/wireguarddashboard/src
      - ./Global-Configs/Master-Key:/opt/wireguarddashboard/src/master-key
    env_file:
      - ./Global-Configs/WireGate-Deploy-ENV/wiregate.env
    ports:
      - "${WG_DASH_PORT_MAPPINGS}"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      private_network:
        ipv4_address: 10.2.0.3


  darkwire:
    depends_on: [wiregate]
    container_name: darkwire
    image: noxcis/darkwire:hydra
    env_file:
      - ./Global-Configs/WireGate-Deploy-ENV/wiregate.env
    networks:
      private_network:
        ipv4_address: 10.2.0.4
    dns: 10.2.0.100

volumes:
    wgd_app:
    wgd_configs:
  